// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1fXQmvZDwUNxs0FgoixhOgV9xsIBSfVQ',
    appId: '1:493165548306:web:758c7fb960ab3942e519cb',
    messagingSenderId: '493165548306',
    projectId: 'instagram-1cbd5',
    authDomain: 'instagram-1cbd5.firebaseapp.com',
    storageBucket: 'instagram-1cbd5.appspot.com',
    measurementId: 'G-1DVZ248PB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9BHUP6nOxo5H0HV2phndaxXjK2KlcEO0',
    appId: '1:493165548306:android:12676fecabe828d7e519cb',
    messagingSenderId: '493165548306',
    projectId: 'instagram-1cbd5',
    storageBucket: 'instagram-1cbd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3IvRwZfK_bgekgCp2tjUynvBKgzGU2So',
    appId: '1:493165548306:ios:ab2a7a247a675ad8e519cb',
    messagingSenderId: '493165548306',
    projectId: 'instagram-1cbd5',
    storageBucket: 'instagram-1cbd5.appspot.com',
    iosClientId: '493165548306-8skjr7ic80uj37d2b621uojjodvspa08.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3IvRwZfK_bgekgCp2tjUynvBKgzGU2So',
    appId: '1:493165548306:ios:9d07c3fd21c47a14e519cb',
    messagingSenderId: '493165548306',
    projectId: 'instagram-1cbd5',
    storageBucket: 'instagram-1cbd5.appspot.com',
    iosClientId: '493165548306-0ehhhr53i3glolqoshep0dgfa9imiac5.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone.RunnerTests',
  );
}
